
server:
  port: ${PORT}

spring:
  application:
    name: test-bank

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DATA_SOURCE_PASSWORD}
    url: ${DATABASE_URL}

  jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true